defaults: &defaults
  name: veeKudos
  kudo_categories: ['awesome','well done','proud','great job','congratulation','thanks']
  company_emoji: ':veepee:'
  :slack_api:
    :base_uri: https://slack.com/api
    :postMessage: /chat.postMessage
    :scheduleMessage: /chat.scheduleMessage
  :web_hooks:
    :base_uri: https://hooks.slack.com/services

development:
  <<: *defaults
  name: veeKudos Development

production:
  <<: *defaults
  name: veeKudos

test: &test
  <<: *defaults
  name: veeKudos Testing