defaults: &defaults
  name: veeKudos
  kudo_categories: ['awesome','well done','proud','great job','congratulation','thanks']

development:
  <<: *defaults
  name: veeKudos Development

production:
  <<: *defaults
  name: veeKudos

test: &test
  <<: *defaults
  name: veeKudos Testing